# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('idMachine', models.AutoField(primary_key=True, serialize=False)),
                ('nameMachine', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Machine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('idModelMachine', models.AutoField(primary_key=True, serialize=False)),
                ('nameModelMachine', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'ModelMachine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeriesMachine',
            fields=[
                ('idSeriesMachine', models.AutoField(primary_key=True, serialize=False)),
                ('nameSeriesMachine', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'SeriesMachine',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='idModelMachine',
            field=models.ForeignKey(db_column='idModelMachine', on_delete=django.db.models.deletion.CASCADE, to='machine.ModelMachine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='idSeriesMachine',
            field=models.ForeignKey(db_column='idSeriesMachine', on_delete=django.db.models.deletion.CASCADE, to='machine.SeriesMachine'),
        ),
    ]
