# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='modelmachine',
            name='status',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='seriesmachine',
            name='status',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
