# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('nameCategory', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('idCriteria', models.AutoField(primary_key=True, serialize=False)),
                ('nameCriteria', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Criteria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DrillBit',
            fields=[
                ('idDrillBit', models.AutoField(primary_key=True, serialize=False)),
                ('codeDrillBit', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'DrillBit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('idMotive', models.AutoField(primary_key=True, serialize=False)),
                ('nameMotive', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Motive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('idPolymer', models.AutoField(primary_key=True, serialize=False)),
                ('namePolymer', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Polymer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('idSection', models.AutoField(primary_key=True, serialize=False)),
                ('nameSection', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('idState', models.AutoField(primary_key=True, serialize=False)),
                ('nameState', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'State',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('idSubSection', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubSection', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'SubSection',
                'managed': True,
            },
        ),
    ]
