# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMotor',
            fields=[
                ('idModelMotor', models.AutoField(primary_key=True, serialize=False)),
                ('nameModelMotor', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'ModelMotor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('idMotor', models.AutoField(primary_key=True, serialize=False)),
                ('nameMotor', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
                ('idModelMotor', models.ForeignKey(db_column='idModelMotor', on_delete=django.db.models.deletion.CASCADE, to='motor.ModelMotor')),
            ],
            options={
                'db_table': 'Motor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeriesMotor',
            fields=[
                ('idSeriesMotor', models.AutoField(primary_key=True, serialize=False)),
                ('nameSeriesMotor', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'SeriesMotor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='motor',
            name='idSeriesMotor',
            field=models.ForeignKey(db_column='idSeriesMotor', on_delete=django.db.models.deletion.CASCADE, to='motor.SeriesMotor'),
        ),
    ]
