# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('idAssistant', models.AutoField(primary_key=True, serialize=False)),
                ('nameAssistant', models.CharField(max_length=250)),
                ('firstLastNameAssistant', models.CharField(max_length=250)),
                ('secondLastNameAssistant', models.CharField(max_length=250)),
                ('dniAssistant', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Assistant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('idWorker', models.AutoField(primary_key=True, serialize=False)),
                ('nameWorker', models.CharField(max_length=250)),
                ('firstLastNameWorker', models.CharField(max_length=250)),
                ('secondLastNameWorker', models.CharField(max_length=250)),
                ('dniWorker', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=3)),
                ('regDate', models.DateTimeField(auto_now_add=True, db_column='reg_date', null=True)),
                ('regUser', models.CharField(blank=True, db_column='reg_user', default='admin', max_length=30, null=True)),
                ('modDate', models.DateTimeField(auto_now=True, db_column='mod_date', null=True)),
                ('modUser', models.CharField(blank=True, db_column='mod_user', default='admin', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Worker',
                'managed': True,
            },
        ),
    ]
